### ISSUE TITLE
Segmentation fault on startup, on Debian and Ubuntu

### ISSUE THREAD

**Issue by ptomato** [ptomato/Beams#3]
Due to an external bug (https://github.com/enthought/chaco/issues/273 -> https://github.com/enthought/enable/issues/97) image plots in Chaco have started causing segmentation faults in Debian and Ubuntu. Apparently compiling Enable without optimization, or with GCC <= 4.6, or with Clang, will solve the problem.

Here is an Ubuntu issue to start building the `python-enable` package with `-O0`: https://bugs.launchpad.net/ubuntu/+source/python-chaco/+bug/1145575

Investigate if compiling without optimization does solve the problem, and if so, publish a patched package on the Beams website.

**Comment by trygentoo** [comment]
I've tried to compile dev-python/enable-4.4.1 with CFLAGS="-O0", but still have the same Segmentation fault.

**Comment by trygentoo** [comment]
Solved problem with segmentation fault by switching to phyton2.7 (3.4 is default), but seems it don't work propertly: led of the webcam is on, but app don't capture any image from cam:
![image](https://cloud.githubusercontent.com/assets/14029458/9569051/5d5dbf3e-4f66-11e5-8e89-2c1cbdd14082.png)

console output is following (with errors rising during beams manipulation):
`/usr/lib64/python2.7/site-packages/traits/trait_handlers.py:1599: FutureWarning: comparison to `None` will result in an elementwise object comparison in the future.
  if value in self.values:
/usr/lib64/python2.7/site-packages/chaco/image_data.py:190: FutureWarning: comparison to `None` will result in an elementwise object comparison in the future.
  self._data = newdata
/usr/lib64/python2.7/site-packages/chaco/array_data_source.py:123: FutureWarning: comparison to `None` will result in an elementwise object comparison in the future.
  self._data = newdata
/usr/lib64/python2.7/site-packages/chaco/axis.py:498: FutureWarning: comparison to `None` will result in an elementwise object comparison in the future.
  for tickpos in mapped_tick_positions]))
/usr/lib64/python2.7/site-packages/chaco/axis.py:499: FutureWarning: comparison to `None` will result in an elementwise object comparison in the future.
  self._tick_label_list = tick_list
/usr/lib64/python2.7/site-packages/chaco/axis.py:500: FutureWarning: comparison to `None` will result in an elementwise object comparison in the future.
  self._tick_label_positions = self._tick_positions
Exception occurred in traits notification handler.
Please check the log file for details.
Exception occurred in traits notification handler for object: <beams.CameraImage.CameraImage object at 0x7fe1fadf1290>, trait: cmap, old value: <function bone at 0x7fe1fae55a28>, new value: <function awesome at 0x7fe1fae559b0>
Traceback (most recent call last):
  File "/usr/lib64/python2.7/site-packages/traits/trait_notifiers.py", line 340, in __call__
    self.handler( *args )
  File "build/bdist.linux-x86_64/egg/beams/CameraImage.py", line 97, in _cmap_changed
    self._image.color_mapper = cmap_func(self._image.value_range)
  File "/usr/lib64/python2.7/site-packages/chaco/default_colormaps.py", line 130, in cmap
    return func(range, **traits)
  File "build/bdist.linux-x86_64/egg/beams/AwesomeColorMaps.py", line 58, in awesome
    N.loadtxt('../data/awesomecolormap.csv', delimiter=','),
  File "/usr/lib64/python2.7/site-packages/numpy/lib/npyio.py", line 737, in loadtxt
    fh = iter(open(fname, 'U'))
IOError: [Errno 2] No such file or directory: '../data/awesomecolormap.csv'
Exception occurred in traits notification handler for object: <beams.CameraImage.CameraImage object at 0x7fe1fadf1290>, trait: cmap, old value: <function bone at 0x7fe1fae55a28>, new value: <function awesome at 0x7fe1fae559b0>
Traceback (most recent call last):
  File "/usr/lib64/python2.7/site-packages/traits/trait_notifiers.py", line 520, in _dispatch_change_event
    self.dispatch( handler, *args )
  File "/usr/lib64/python2.7/site-packages/traits/trait_notifiers.py", line 615, in dispatch
    handler( *args )
  File "build/bdist.linux-x86_64/egg/beams/ColorMapEditor.py", line 110, in update_editor
    self.control.set_cmap(self.value.cmap)
  File "build/bdist.linux-x86_64/egg/beams/ColorMapEditor.py", line 67, in set_cmap
    mapper = self.cmap(DataRange1D(low=0, high=255))
  File "build/bdist.linux-x86_64/egg/beams/AwesomeColorMaps.py", line 58, in awesome
    N.loadtxt('../data/awesomecolormap.csv', delimiter=','),
  File "/usr/lib64/python2.7/site-packages/numpy/lib/npyio.py", line 737, in loadtxt
    fh = iter(open(fname, 'U'))
IOError: [Errno 2] No such file or directory: '../data/awesomecolormap.csv'
Traceback (most recent call last):
  File "/usr/lib64/python2.7/site-packages/traitsui/qt4/ui_live.py", line 194, in _on_finished
    self.close(accept)
  File "/usr/lib64/python2.7/site-packages/traitsui/qt4/ui_live.py", line 182, in close
    super(_LiveWindow, self).close(rc)
  File "/usr/lib64/python2.7/site-packages/traitsui/qt4/ui_base.py", line 438, in close
    self.ui.dispose(rc)
  File "/usr/lib64/python2.7/site-packages/traitsui/ui.py", line 240, in dispose
    self.finish()
  File "/usr/lib64/python2.7/site-packages/traitsui/ui.py", line 275, in finish
    self.handler.closed( self.info, self.result )
  File "build/bdist.linux-x86_64/egg/beams/MainHandler.py", line 78, in closed
  File "build/bdist.linux-x86_64/egg/beams/Webcam.py", line 52, in close
AttributeError: 'module' object has no attribute 'ReleaseCapture'
`

**Comment by ptomato** [comment]
That seems to be a separate bug than this one (#4).

**Comment by ptomato** [comment]
I've added a patched `python-enable` package to the [download page](http://ptomato.name/opensource/beams/beams-download.html); see near the bottom. Please let me know if this package works for you.

**Comment by trygentoo** [comment]
Hello,

with your patch it works somehow:
![image](https://cloud.githubusercontent.com/assets/14029458/9599571/852aa828-509d-11e5-9fdb-d9410fdd7fd7.png)
But I can't switch from internal laptop webcam to external which is going to work as beamprofiler.
When I go to "Choose camera..." menu there only 2 options OpenCV and Dummy Gauss. Moreover app is stunned if OpenCV chosen after alert "No camera was detected. Did you forget to plug it in?"
Console output:
```bash
/usr/lib64/python2.7/site-packages/traits/trait_handlers.py:1599: FutureWarning: comparison to `None` will result in an elementwise object comparison in the future.
  if value in self.values:
/usr/lib64/python2.7/site-packages/chaco/image_data.py:190: FutureWarning: comparison to `None` will result in an elementwise object comparison in the future.
  self._data = newdata
/usr/lib64/python2.7/site-packages/chaco/array_data_source.py:123: FutureWarning: comparison to `None` will result in an elementwise object comparison in the future.
  self._data = newdata
/usr/lib64/python2.7/site-packages/chaco/axis.py:498: FutureWarning: comparison to `None` will result in an elementwise object comparison in the future.
  for tickpos in mapped_tick_positions]))
/usr/lib64/python2.7/site-packages/chaco/axis.py:499: FutureWarning: comparison to `None` will result in an elementwise object comparison in the future.
  self._tick_label_list = tick_list
/usr/lib64/python2.7/site-packages/chaco/axis.py:500: FutureWarning: comparison to `None` will result in an elementwise object comparison in the future.
  self._tick_label_positions = self._tick_positions
Exception occurred in traits notification handler.
Please check the log file for details.
Exception occurred in traits notification handler for object: <beams.MainWindow.MainWindow object at 0x7f7f3f317110>, trait: camera, old value: <beams.Webcam.Webcam object at 0x7f7f3f277290>, new value: <beams.Webcam.Webcam object at 0x7f7f3022e6b0>
Traceback (most recent call last):
  File "/usr/lib64/python2.7/site-packages/traits/trait_notifiers.py", line 520, in _dispatch_change_event
    self.dispatch( handler, *args )
  File "/usr/lib64/python2.7/site-packages/traits/trait_notifiers.py", line 615, in dispatch
    handler( *args )
  File "/usr/lib64/python2.7/site-packages/traitsui/ui.py", line 824, in _evaluate_when
    self._do_evaluate_when(at_init=False)
  File "/usr/lib64/python2.7/site-packages/traitsui/ui.py", line 838, in _do_evaluate_when
    self._evaluate_condition(self._visible, 'visible', at_init)
  File "/usr/lib64/python2.7/site-packages/traitsui/ui.py", line 883, in _evaluate_condition
    context = self._get_context( self.context )
  File "/usr/lib64/python2.7/site-packages/traitsui/ui.py", line 804, in _get_context
    context2 = value.trait_get()
  File "/usr/lib64/python2.7/site-packages/traits/has_traits.py", line 1485, in trait_get
    value = getattr( self, name, Missing )
  File "build/bdist.linux-x86_64/egg/beams/Webcam.py", line 62, in _resolution_default
    width = cv.GetCaptureProperty(self._capture, FRAME_WIDTH)
TypeError: Expected CvCapture for argument 'capture'
libv4l2: error setting pixformat: Device or resource busy
HIGHGUI ERROR: libv4l unable to ioctl S_FMT
libv4l2: error setting pixformat: Device or resource busy
libv4l1: error setting pixformat: Device or resource busy
HIGHGUI ERROR: libv4l unable to ioctl VIDIOCSPICT
```

**Comment by ptomato** [comment]
OK, I opened #5 for this. If you can help at all, that would be appreciated; I don't have access to an external webcam right now to try this out.
